# Setup
title:            Sammy Levy
tagline:          'Portfolio'
description:      "Hello! Welcome to my portfolio! Currently, I'm an undergraduate student at Occidental College pursuing a degree in computer science"
url:              https://slevy14.github.io
baseurl:          ''
paginate:         5
paginate_path:    "/blog/page:num"

# About and contact
author:
  name:           'Sammy Levy'
  url:            https://github.com/slevy14/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
