# Setup
title:            Sammy Levy
tagline:          'Portfolio'
description:      'This is a test to see if this text ends up where i think it will in the sidebar'
url:              https://slevy14.github.io
baseurl:          ''
paginate:         5
paginate_path:    "/blog/page:num"

# About and contact
author:
  name:           'Sammy Levy'
  url:            https://github.com/slevy14/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
